---

- name: Create databases on database servers
  hosts: db_servers
  gather_facts: true

  vars_files:
    - secrets.yml

  tasks:
    - name: Create new database on servers
      community.general.mssql_db:
        login_host: "{{ mssql_hostname }}"
        login_user: "{{ mssql_user }}"
        login_password: "{{ mssql_password }}"
        # login_host: localhost
        # login_user: sa
        # login_password: redhat123!
        name: aap-db-2
        state: present