---

- name: Create databases on database servers
  hosts: db_servers
  gather_facts: true
  become: true

  vars_files:
    - secrets.yml

  tasks:
    - name: Create new database on servers
      community.general.mssql_db:
        login_host: "{{ mssql_hostname }}"
        login_user: "{{ mssql_user }}"
        login_password: "{{ mssql_password }}"
        name: aap-db-3
        state: present

    - name: Show database tables
      register: output
      ansible.builtin.command: sqlcmd -S "{{ mysql_hostname }}" -U "{{ mysql_user }}" -P "{{ mysql_password }}" -C