---

- name: Test secret variable from vault
  hosts: db_servers
  gather_facts: false

  # vars_files:
  #   - secrets.yml

  tasks:

    - name: Print hello world message
      ansible.builtin.debug:
        msg: "The value is: bar"
